name: JerylPlugin
version: 1.5
main: org.example.Main
api-version: '26.2'
author: Jeryl Angelo
description: My first Spigot plugin created in IntelliJ!

commands:
  jerylplugin:
    description: this shit plugin does some shit
    usage: /jerylplugin [help]
    aliases: [jp]


  smite:
    description: For you have been naughty
    usage: /smite <player>
    permission: jerylplugin.smite
    permission-message: You do not have permission to use this command!

  cocopops:
    description: Wilson's favourite cereal
    usage: /cocopops

  airstrike:
    description: Nice!
    usage: /airstrike

  huntingrifle:
    description: Turns a spyglass into a lucas hunter
    usage: /huntingrifle
